## Векторы

Сложение, вычитание и умножение на число векторов

In [9]:
import numpy as np
s = np.array([2, 3, 2.5])
f = np.array([120, 150, 190])
m = np.array([130, 130, 130])
a = 72
res = s*a
res
#common = res + f + m
#common

array([144., 216., 180.])

In [6]:
rot = np.array([3, 4, 5, 9])
price = 200
sold = np.array([1, 5, 3, 6])
rot_price = rot * price
income = 400
sold_income = sold * income
res = sold_income - rot_price
res

array([-200, 1200,  200,  600])

Скалярное произведение

In [7]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0

Таким образом, в линейной алгебре длина вектора определяется как квадратный корень из скалярного произведения вектора с самим собой.

ПРАКТИКА

In [2]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [3]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

In [7]:
Hut_Paradise_values[4]
Hut_Paradise_values[:, 3]
unlivearea = Hut_Paradise_values[:, 1] - Hut_Paradise_values[:, 5]
unlivearea

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [13]:
time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20]) 
all_time = Hut_Paradise_values[:, 4] * time
all_time_list = list(all_time)
sum(all_time_list)

1348

In [14]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [15]:
lin = 2*v + (-3)*w
lin

array([-3, 14,  3,  4,  2])

In [16]:
print('(lin,u):',np.dot(lin,u))

(lin,u): 0


## МАТРИЦЫ

In [17]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [20]:
A.shape
# (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

a_23= 1 a_32= 3 a_33= 1


Практика

In [40]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [31]:

import pandas as pd

Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
print(Inc[0, 0], Inc[1, 1], Inc[2, 2])

Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
Cons
print(Cons[0, 0], Cons[1, 1], Cons[2, 2])

100 200 100
50 80 140


In [36]:
Inc_nalog = Inc*0.87
Inc_nalog[0]

array([ 87. , 130.5,  78.3])

In [39]:
P = Inc_nalog - Cons
P[2]

array([ 61.8, -26.9, -53. ])

In [1]:
# 6.9

import numpy as np

# a = np.array([1, 1])
# b = np.array([2, -1])
# c = np.array([1, 2])

# matrix = np.array([a, b, c])
# matrix_T = G.T

# G = np.dot(matrix, matrix_T)
# G


A = np.matrix([[1, 2, 1], [1, -1, 2]])
A.T @ A

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])

In [8]:
A = np.array([[1, 1], [1, 2]])
A.T@A

array([[2, 3],
       [3, 5]])